version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GID: ${GROUP_ID}
        UID: ${USER_ID}
    volumes:
      - ./var/home:/home/user
      - ./:/home/user/app
      - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket
    environment:
      PULSE_SERVER: unix:/tmp/pulseaudio.socket
      PULSE_COOKIE: /tmp/pulseaudio.cookie
